# This file was generated by GoReleaser. DO NOT EDIT.
cask "cenvero-fleet" do
  version "2.4.0"

  on_macos do
    on_intel do
      sha256 "fbfd9137b715f2a78e9a7ecfa9fc0699f1119ec09d7f726598e145b0bef10204"
      url "https://github.com/cenvero/fleet/releases/download/v#{version}/fleet_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a7dafb0b5d9c7caf2c6ab038c1796a595b52df73f434e91406f1db6e58e51267"
      url "https://github.com/cenvero/fleet/releases/download/v#{version}/fleet_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9a913c24b3c10411d6f1d993af1f30b3c7fb6b4176aab826fbaa80a9861737fd"
      url "https://github.com/cenvero/fleet/releases/download/v#{version}/fleet_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ab5b64b33c3a09bf2f31b6510bf55ac2bd8e94030e1b23fa9b9ad30a443a5c70"
      url "https://github.com/cenvero/fleet/releases/download/v#{version}/fleet_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cenvero-fleet"
  desc "Self-hosted decentralized fleet management platform"
  homepage "https://fleet.cenvero.org"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fleet"

  # No zap stanza required

end
