# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CenveroFleet < Formula
  desc "Self-hosted decentralized fleet management platform"
  homepage "https://fleet.cenvero.org"
  version "1.5.2"
  license "AGPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cenvero/fleet/releases/download/v1.5.2/fleet_1.5.2_darwin_amd64.tar.gz"
      sha256 "edb83570f6bc1d96bbf52f24825588948972e6968fd9be85cbdd0838425d21dc"

      define_method(:install) do
        bin.install "fleet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cenvero/fleet/releases/download/v1.5.2/fleet_1.5.2_darwin_arm64.tar.gz"
      sha256 "6adcfd2e4d1317e8129353a6cfa638dc52cfe0375f29ee0c1e06597bd58d89eb"

      define_method(:install) do
        bin.install "fleet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cenvero/fleet/releases/download/v1.5.2/fleet_1.5.2_linux_amd64.tar.gz"
      sha256 "5c0fd57ee4d7082307336181b44d6f6a0eed126026220e69abf2255fb357b6cb"
      define_method(:install) do
        bin.install "fleet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cenvero/fleet/releases/download/v1.5.2/fleet_1.5.2_linux_arm64.tar.gz"
      sha256 "3023c8aef2d62cc8006f385a6e1a50627cdba22477895bc781ce521b2e23bd7a"
      define_method(:install) do
        bin.install "fleet"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/fleet --version")
  end
end
