# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CenveroFleet < Formula
  desc "Self-hosted decentralized fleet management platform"
  homepage "https://fleet.cenvero.org"
  version "2.4.3"
  license "AGPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cenvero/fleet/releases/download/v2.4.3/fleet_2.4.3_darwin_amd64.tar.gz"
      sha256 "cc4179f3a2dbfd336c2ede977c0c52b2f1e931fafbfec78c8be721c6b396c178"

      define_method(:install) do
        bin.install "fleet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cenvero/fleet/releases/download/v2.4.3/fleet_2.4.3_darwin_arm64.tar.gz"
      sha256 "ca06bb68e969abb29255e48d2c48fc8be73d60b9d4ea9938c7f07f1a58726f24"

      define_method(:install) do
        bin.install "fleet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cenvero/fleet/releases/download/v2.4.3/fleet_2.4.3_linux_amd64.tar.gz"
      sha256 "278f1683e21ab8323e1df527821b7c3c17e4482509665196e13101a7c08731db"
      define_method(:install) do
        bin.install "fleet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cenvero/fleet/releases/download/v2.4.3/fleet_2.4.3_linux_arm64.tar.gz"
      sha256 "d7d7f55f0fbad91e3c42fb02053c64af0cf062ea39da7a9b65bbf3ec11e0fc34"
      define_method(:install) do
        bin.install "fleet"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/fleet --version")
  end
end
